import { describe, expect, it } from "vitest";
import { WORLDS } from "./worlds";
import { resolveWorld } from "./resolve";

// ── text tone ───────────────────────────────────────────────────────────────

describe("text tone", () => {
	// Generated by scripts/measure-text-tone.py from the planet art. These
	// assertions pin the contract the generator must keep, not the values it
	// produced — a regenerated file that broke any of them would be wrong.
	const srgb = (c: number) => {
		const v = c / 255;
		return v <= 0.03928 ? v / 12.92 : ((v + 0.055) / 1.055) ** 2.4;
	};
	const lum = (hex: string) =>
		0.2126 * srgb(parseInt(hex.slice(1, 3), 16)) +
		0.7152 * srgb(parseInt(hex.slice(3, 5), 16)) +
		0.0722 * srgb(parseInt(hex.slice(5, 7), 16));

	it("gives every world a tone and a text color", () => {
		for (const world of WORLDS) {
			expect(world.textTone, world.id).toMatch(/^(light|dark)$/);
			// 6 digits, or 8 when it carries alpha (dark text is #222222CC).
			expect(world.textColor, world.id).toMatch(/^#[0-9A-F]{6}([0-9A-F]{2})?$/);
		}
	});

	it("uses one shared token for dark text so the art tints it", () => {
		// A per-world dark color amplified hue artifacts: Crait's near-white
		// #FDFCED darkened into olive. One translucent token lets the image
		// supply the tint instead.
		const dark = WORLDS.filter((w) => w.textTone === "dark");
		expect(new Set(dark.map((w) => w.textColor)).size).toBe(1);
		expect(dark[0].textColor).toHaveLength(9);
	});

	it("keeps the text color on the correct side of its tone", () => {
		// A "light" tone whose color came out dark would be the bug that shipped
		// during development: the generator only knew how to darken, so Exegol —
		// on near-black art — was pushed the wrong way.
		for (const world of WORLDS) {
			const l = lum(world.textColor);
			if (world.textTone === "light") expect(l, world.id).toBeGreaterThan(0.15);
			else expect(l, world.id).toBeLessThan(0.35);
		}
	});

	it("resolves the text color through to the view layer", () => {
		const resolvedWorld = resolveWorld("clear_temperate");
		expect(resolvedWorld.textColor).toMatch(/^#[0-9A-F]{6}([0-9A-F]{2})?$/);
		expect(resolvedWorld.textTone).toMatch(/^(light|dark)$/);
	});

	it("only needs dark text where the art is genuinely bright", () => {
		// Sanity bound, not a snapshot: if a regeneration flipped most of the
		// catalog to dark text, something is wrong with the measurement.
		const dark = WORLDS.filter((w) => w.textTone === "dark");
		expect(dark.length).toBeGreaterThan(0);
		expect(dark.length).toBeLessThan(WORLDS.length / 3);
	});
});
