/**
 * Regenerates shared/weather-slot-matrix.json — the cross-platform parity
 * fixture.
 *
 * Both test suites assert their own `getSlotForWeather` against this file, so
 * the web and iOS mappers can't drift apart without one of them going red.
 * The web implementation is the source of truth: it is generated from here and
 * the Swift port is checked against it.
 *
 * Run after any intentional change to the condition table or a temperature
 * band, and review the resulting diff — it shows exactly which weather now
 * resolves differently.
 *
 *   npm run matrix
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import {
	getSlotForWeather,
	convertKelvinToFahrenheit,
} from "../src/app/utils/weatherDescriptions";

/** Every condition code OpenWeather documents, grouped for readability. */
const CODES: readonly number[] = [
	// 2xx thunderstorm
	200, 201, 202, 210, 211, 212, 221, 230, 231, 232,
	// 3xx drizzle
	300, 301, 302, 310, 311, 312, 313, 314, 321,
	// 5xx rain
	500, 501, 502, 503, 504, 511, 520, 521, 522, 531,
	// 6xx snow
	600, 601, 602, 611, 612, 613, 615, 616, 620, 621, 622,
	// 7xx atmosphere
	701, 711, 721, 731, 741, 751, 761, 762, 771, 781,
	// 8xx clear and clouds
	800, 801, 802, 803, 804,
];

/**
 * Every band boundary and the degree below it, plus both extremes. Any change
 * to a cutoff moves at least one of these, so the diff can't be silent.
 */
const PROBE_TEMPS_F: readonly number[] = [
	-60, 31, 32, 44, 45, 57, 58, 68, 69, 78, 79, 89, 90, 99, 100, 140,
];

/** `main` is only a fallback, but it has to be something — derive it. */
const mainForCode = (code: number): string => {
	if (code >= 800) return code === 800 ? "Clear" : "Clouds";
	const group = Math.floor(code / 100);
	return { 2: "Thunderstorm", 3: "Drizzle", 5: "Rain", 6: "Snow", 7: "Mist" }[
		group
	] as string;
};

const toKelvin = (tempF: number): number => ((tempF - 32) * 5) / 9 + 273.15;

const matrix: Record<string, string[]> = {};
for (const code of CODES) {
	matrix[String(code)] = PROBE_TEMPS_F.map((tempF) =>
		getSlotForWeather({
			id: code,
			main: mainForCode(code),
			tempKelvin: toKelvin(tempF),
		})
	);
}

// Sanity: the round-trip through Kelvin must land on the temperature we asked
// for, or the fixture encodes float noise instead of the intended bands.
for (const tempF of PROBE_TEMPS_F) {
	const rounded = Math.floor(convertKelvinToFahrenheit(toKelvin(tempF)) + 0.5);
	if (rounded !== tempF) {
		throw new Error(`probe ${tempF}°F round-trips to ${rounded}°F`);
	}
}

const payload = {
	$comment:
		"GENERATED by web-app/galactic-weather/scripts/generate-slot-matrix.ts — " +
		"do not hand-edit. Run `npm run matrix` and commit the diff.",
	probeTemperaturesF: PROBE_TEMPS_F,
	matrix,
};

const out = join(__dirname, "..", "..", "..", "shared", "weather-slot-matrix.json");
writeFileSync(out, `${JSON.stringify(payload, null, "\t")}\n`);

const cells = CODES.length * PROBE_TEMPS_F.length;
console.log(`wrote ${out}`);
console.log(`${CODES.length} codes × ${PROBE_TEMPS_F.length} temperatures = ${cells} cells`);
console.log(`distinct slots: ${new Set(Object.values(matrix).flat()).size}`);
